/**
 * ============================================================================
 * i18n/en.js  ->  PFM.translations.en  (textos de la interfaz en inglés)
 * ============================================================================
 * Traducciones de la interfaz — inglés. Cada clave debe existir también en el otro
 * idioma (i18n/es.js). Se usan con data-i18n="clave" en el HTML o con
 * PFM.i18n.t('clave') en JS.
 *
 * La convención de claves y los pasos para agregar una clave o un idioma están
 * explicados en la cabecera de i18n/es.js (las claves son idénticas en ambos archivos;
 * solo cambia el texto). Aquí solo se traducen los valores.
 *
 * Carga: debe ir antes de js/core/i18n.js. Añade la entrada `en` a PFM.translations.
 * localStorage: no lee ni escribe nada.
 * Los títulos de sección "NEW TRANSLATIONS..." / "MODIFIED" son notas históricas del
 * desarrollo, sin efecto.
 * ============================================================================
 */
(function (PFM) {
    PFM.translations = PFM.translations || {};
    PFM.translations.en = {
        // GENERAL 
        'app_title': 'Design Thinking Tools for Improvement Activities',
        'main_menu': 'Main Menu',
        'project': 'Project:',
        'unnamed_project': '(Unnamed)',
        
        // NEW TRANSLATIONS FOR DESCRIPTION 
        'project_description': 'Project Description',
        'enter_project_description': 'Describe the objective, scope and details of the project...',
        
        // NEW TRANSLATIONS FOR MODULE SELECTION MENU (descripcion.html)
        'modules_menu_title': 'Select the modules to complete',
        'modules_menu_subtitle': 'Choose which parts of the process you want to complete. Only those pages, results, and PDF sections will be included.',
        'module_initial_analysis': 'Initial Analysis',
        'module_initial_analysis_desc': 'Criteria and weights (project needs)',
        'module_required_badge': 'Required',
        'module_definition_ideas': 'Definition and Analysis of Ideas',
        'module_definition_ideas_desc': 'Initial ideas/concepts and their evaluation',

        // NEW TRANSLATIONS FOR ELEMENT SELECTION (seleccionEvaluar.html)
        'select_elements_title': 'Selection of Elements to Evaluate',
        'select_elements_label': 'SELECTION',
        'select_elements_subtitle': 'Choose the elements you want to include in the evaluation · Edit the name with the pencil icon',
        'select_elements_none': 'No elements available. Enable the "Definition of Ideas" or "Activity Diagram" module on the description page.',
        'select_group_ideas': 'Ideas / Concepts',
        'select_group_tasks': 'Activity Diagram Functions',

        // NEW TRANSLATIONS FOR OPTION DIAGRAMS
        'diagram_question': 'Activity Diagram',
        'ask_diagram': 'Do you want to create the activity diagrams of functions?',
        
        // NEW TRANSLATIONS FOR OPTION CONCEPTS
        'concept_question': 'Exploration and Evaluation of Concepts',
        'ask_concept': 'Do you want to explore and evaluate concepts?',
        
        // NEW TRANSLATIONS FOR OPTION PREVENTION
        'prevention_question': 'Risk Prevention',
        'ask_prevention': 'Do you want to perform risk prevention analysis?',
        
        // BUTTONS (MODIFIED: Separate Save and Continue)
        'save': '💾 Save',
        'continue': '➡️ Continue',
        'back': '◀️ Back',
        'load_necesidades': '📂 Load Needs',
        'save_necesidades': '💾 Save Needs',
        'load_ideas': '📂 Load Ideas',
        'save_ideas': '💾 Save Ideas',
        'load_evaluacion': '📂 Load Evaluation',
        'save_evaluacion': '💾 Save Evaluation',
        'error_loading_file': 'Could not read the file. Make sure it is a valid .txt file generated by this application.',
        'start': '🚀 Start',
        'calculate': '🧮 Calculate',
        'download_pdf': '📄 Download PDF again',
        'return_main_menu': '🏠 Return to main menu',
        'risk_calculation': '⚠️ Calculate risk',
        'theme_light': 'Switch to light mode',
        'theme_dark': 'Switch to dark mode',
        
        // ERRORS
        'error_sum_weights': 'Sum of weights must be exactly 10',
        
        // PAGES
        'description_data': 'Description',
        'criteria_weights': 'Needs and priorities',
        'ideas_concepts': 'Ideas',
        'concept_evaluation': 'Evaluation of ideas',
        'explore_possibilities': 'Explore Options',
        'concept_formation': 'Concept Formation',
        'risk_prevention': 'Risk Prevention',
        'diagram': 'Diagram of functions',
        
        // TABLES 
        'criteria': 'Need',
        'weight': 'Priority',
        'idea': 'Idea',
        'rating': 'Rating (0-10)',
        'result': 'Result',
        'options':'Option',
        'option': 'Concept',
        'possibilities': 'Explore options',
        'tasks_responsibles': 'Linking inputs and outputs through functions/tasks',
        
        // CONCEPTS 
        'best_concept': 'Best Concept',
        'no_concept_selected': 'None selected',
        'concept_composition': 'Options that form this concept:',
        'concept_formed': 'Concept Formed',
        'options_forming_concept': 'Options that form this concept:',
        
        // RISK PREVENTION 
        'potential_failure': 'Potential failure',
        'effect': 'Effect',
        'severity': 'Severity (1-10)',
        'occurrence': 'Occurrence (1-10)',
        'risk': 'Risk',
        'actions_to_take': 'Action/Actions to take',
        'responsible': 'Responsible',
        'today_date': 'Registration date',
        'action_taken': 'Action taken',
        'action_date': 'Date when action was taken',
        'prevention': 'Potential failure',
        
        // DIAGRAMA/TASKS 
        'responsable_label': 'Input',
        'task_label': 'Function',
        'salida_label': 'Output',
        'enter_salida': 'Describe the output',
        'add_row': 'Add row',
        // Avisos de celda/flecha oculta en diagrama.html
        'click_to_show': '👆 Click to show',
        'click_to_show_arrow': '👆 Click to show arrow',
        // Botón de agregar tabla en prevenir.html
        'add_prevention': '+ Add Prevention',
        // Avisos cuando no hay elementos (morfologia, evalConceptos, evaluacion)
        'no_concepts_defined': 'No concepts defined. Go back to the previous page to enter concepts.',
        'no_elements_to_evaluate': 'No elements selected to evaluate. Go back to the previous page and select at least one.',
        // Diálogos (prevenir: confirmar borrado; resultados: falta la librería jsPDF)
        'confirm_delete_prevention': 'Delete this prevention?',
        'error_jspdf_missing': 'Error: the PDF cannot be generated. jsPDF is not loaded.',
        
        // PDF AND RESULTS 
        'pdf_download_info': 'Your project PDF report has been generated and downloaded automatically.',
        'pdf_filename': 'Filename:',
        'report_generated': 'Report generated',
        
        // FORMS 
        'project_name': 'Project name',
        'enter_project_name': 'Enter project name',
        'enter_possibility': 'Enter possibility',
        'enter_rating': 'Enter rating (0-10)',
        'enter_severity': 'Enter severity (1-10)',
        'enter_occurrence': 'Enter occurrence (1-10)',
        'enter_task': 'Enter task',
        'enter_responsible': 'Enter input',
        
        // GC1 (CONCEPT FORMATION) 
        'no_selection': 'No selection',
        
        // EVAL CONCEPTS 
        'evaluation_concepts_formed': 'Evaluation of Formed Concepts',
        'concepts_formed': 'Formed Concepts',
        // ASISTENTE IA (js/features/assistant.js)
        'assistant_title': '🤖 AI Assistant',
        'assistant_toggle': 'AI Assistant',
        'assistant_close': 'Close',
        'assistant_file_ready': '📄 The assistant generated a file ready to use.',
        'assistant_insert': '📥 Insert into the form',
        'assistant_download': '💾 Download .txt',
        'assistant_placeholder': 'Type here...',
        'assistant_send': 'Send',
        'assistant_typing': 'Typing...',
        'assistant_error_generic': 'An error occurred while contacting the assistant.',
        'assistant_error_network': 'Could not reach the assistant. Check your connection and try again.',
        'assistant_inserted': '✅ The data was inserted into the form.',
        'assistant_insert_failed': 'Could not insert automatically. Use "Download .txt" and load it with this page\'s button.',
        'assistant_greeting_necesidades': 'Hi! Let\'s identify the needs and priorities of your project together. Tell me, what is your project about, or which process do you want to improve?',
        'assistant_greeting_ideas': 'Hi! Let\'s generate ideas for your project. What specific problem do you want to solve?',
        'assistant_greeting_evaluacion': 'Hi! Let\'s evaluate your ideas against your criteria. Would you rather go idea by idea, or give me your general opinion first?',
        'assistant_greeting_default': 'Hi! How can I help you?',
        'assistant_mic': 'Dictate by voice',
        'assistant_mic_stop': 'Stop dictation',
        'assistant_listening': 'Listening… speak now',
        'assistant_voice_unsupported': 'Your browser does not support voice dictation. Use Chrome or Edge, or type your message.',
        'assistant_voice_denied': 'Could not use the microphone. Allow microphone access in your browser (the page must be opened over HTTPS).',
        'assistant_voice_no_speech': 'Nothing was heard. Press the microphone and try again.',
        'assistant_voice_no_mic': 'No microphone was found. Connect one and try again.',
        'assistant_voice_network': 'The browser voice service is unavailable. Check your connection.',
        'assistant_voice_error': 'Could not start voice dictation.',

        
        // FOOTER 
        'footer_text': 'José Luis Rodríguez Téllez — Salvador González García'
    };
})(window.PFM = window.PFM || {});
